### ISSUE TITLE
Item Duplication bug

### ISSUE THREAD

**Issue by THEAN24** [MelanX/ExtraDisks#11]
Hi I would like to report an issue about Item duplication, I don't know if Refined Storage has a bug because of the beta version or Extra Disk mod. So what happens is that everytime I leave an item (like a single sword) in the system using one of "Extra Disk" disks it seems it doubles up or just multiplies to hundreds. Like I placed a dirt block in the system then after several minutes later it multiplied to 128 and when I pull all those dirt blocks out it just gives me a single dirt like what I put earlier. I use a automated farm for other blocks but not dirt blocks.

Hopefully you can fix this and also if ever its not Extra Disk I already reported to Refined Storage.

Here is a reference vid: https://drive.google.com/file/d/1p2eDn-i1stDpws89iVdW40os5SQ2d4Wm/view?usp=sharing

**Comment by MelanX** [comment]
Did you "copy" the disks with middle mouse click?
If not, is it possible to provide a world download and modpack download?

**Comment by THEAN24** [comment]
No I did not copy any nor duplicate any disks.

OK. Also I emptied the disk drives and put new disk in it.




> 
> 
> Did you "copy" the disks with middle mouse click?
> If not, is it possible to provide a world download and modpack download?

No I did not copy any nor duplicate any disks.

OK. Also I emptied the disk drives and put new disk in it.

https://drive.google.com/file/d/1_0kIMhMnPDaSotjX65RDx6V0NjzkApaF/view?usp=sharing

**Comment by THEAN24** [comment]
I think I just answered the problem, it seems that there is a bug in refined storage but I'm still not sure about it or maybe some other mods are affecting this problems

**Comment by THEAN24** [comment]
> 
> 
> I think I just answered the problem, it seems that there is a bug in refined storage but I'm still not sure about it or maybe some other mods are affecting this problems

Try adding a single item in the system the rejoiin the world then you'll see

**Comment by MelanX** [comment]
You **did** copy the disks.
They all have the same uuid (the line under Stored)
![image](https://user-images.githubusercontent.com/26039509/79595507-46140180-80df-11ea-9b34-6de7303c11b7.png)
