### ISSUE TITLE
[1.16] 16384k_fluid_storage_part uncraftable

### ISSUE THREAD

**Issue by NillerMedDild** [MelanX/ExtraDisks#16]
The recipe that should have the `16384k_fuid_storage_part` is actually for the disk, gonna pr the fix in a bit.

**Comment by MelanX** [comment]
Oh true, I did a mistake in data generation. Will fix it tomorrow. Your PR will be closed because it just changes the json but will be overwritten once I generate data again. Need to fix it in code.

**Comment by NillerMedDild** [comment]
Cool :)
