### ISSUE TITLE
1024K_storage_part

### ISSUE THREAD

**Issue by lacomarca** [MelanX/ExtraDisks#19]
Hi,

I'm having problems creating patterns for a infinite disk drive. Seems that there is a problem with the recipe for this part. Instead of taking 1024 storage part is taking storagepart_1024k. Other parts are correct. Could you please solve it?

I'm using:

Forge 34.1.19
Minecraft: 1.16.3
Extradisks: extradisks-1.16.3-1.3.3

Thanks!

**Comment by MelanX** [comment]
I crafted this one yesterday. Could you show me a screenshot for that?

**Comment by lacomarca** [comment]
Hope those screenshots could help:

https://gyazo.com/68bfed016d4aa695cdac61b061d2ce13
https://gyazo.com/f4d260c2f8aa33b85005b4dc5f65ff04

As you can see, others are working normally, it doesn't work only the 256k one.

**Comment by MelanX** [comment]
You should report it to Extra Storage, that’s not my mod

**Comment by lacomarca** [comment]
But the thing is that here should appear your part instead of Extra Storage part. Should I report this to Extra Storage anyway?

**Comment by MelanX** [comment]
Oh.. if you’re using both, you should delete the recipes for the other mod. But that way you can’t use the storage block (or you add the recipes with my mod)
If it’s a modpack, you should report this Problem to the modpack author.
