### ISSUE TITLE
Original crafters not working

### ISSUE THREAD

**Issue by lacomarca** [MelanX/ExtraDisks#20]
Hi,

Since I added extra disks the original crafters from RS are not working. I need to use only yours: iron, golden, etc. As well, that would be amazing if recipe for your crafters could take colored crafters as well (only taking the normal original one).

Could you please solve that issue? 

Hope you can help. I love your mod :)

Forge 34.1.19
Minecraft: 1.16.3
Extradisks: extradisks-1.16.3-1.3.3

Thanks!

**Comment by MelanX** [comment]
I don’t add any crafters

**Comment by lacomarca** [comment]
Sorry, I messed with ExtraStorage
