### ISSUE TITLE
[1.16.4 - 1.4] Fluid storage blocks fail to create network node

### ISSUE THREAD

**Issue by WhitePhant0m** [MelanX/ExtraDisks#22]
~~All storage blocks seem to be missing a loot table which allows them to drop when broken.
Edit: Seems like they do have loot tables, but when trying to break them, they do not drop.~~
Edit2: From the looks of it, they just don't want to break in general, I'll upload a gif of it as soon as I can.
Edit3: They seem to crash the server when trying to break them with other methods than just hand/pick.
[![Image from Gyazo](https://i.gyazo.com/e8ba939a659877e0bf1bf0157f26b7f3.gif)](https://gyazo.com/e8ba939a659877e0bf1bf0157f26b7f3)
[Crash from using a block breaker](https://paste.gg/p/wphant0m/de1a15c82fce4f7c93640df95c6686eb)
[Crash from left clicking with world edit wand](https://paste.gg/p/wphant0m/0b2adf429c2a4eef842b204da8d0ec83)
Tho from looking those crash logs, maybe I should report this to Refined storage? Since I don't see this mod appearing in the logs much...

**Comment by MelanX** [comment]
Could you please provide a latest.log from placing and removing a storage block?

**Comment by WhitePhant0m** [comment]
https://paste.gg/p/wphant0m/c55134ec2eba4be6820288ba150669d8
I think that should have it, there are multiple since I caused multiple crashes and I'm not exactly sure which it is, but this seems to have related errors in it

**Comment by MelanX** [comment]
I can't see the part where you place the block.
Does this happen with Refined Storage storage blocks, too?

**Comment by WhitePhant0m** [comment]
Hmm... doesn't seem to happen anymore, so don't know if refined storage blocks do it too.

**Comment by WhitePhant0m** [comment]
OH, it's only the fluids ones

**Comment by MelanX** [comment]
Oh yes, something is wrong with my fluid storage blocks. Thank you, I will try to fix it as soon as possible,

**Comment by MelanX** [comment]
1.4.2 is available soon

**Comment by WhitePhant0m** [comment]
oh, there is still the issue of normal storage blocks not dropping when broken

**Comment by MelanX** [comment]
I can't reproduce this issue. For me, all the storage blocks drop the correct item. Maybe it was because of the fluid storage blocks. Would be cool if you could test it and let me know. And if it still happens, a new latest.log would be very nice

**Comment by WhitePhant0m** [comment]
https://gyazo.com/831ed809b5cbb83b0c0062ac237bf76b
I'll test it after getting the update

**Comment by MelanX** [comment]
Oh, i see.. you don't have to try. I see. Will be fixed :D

**Comment by MelanX** [comment]
The problem is much bigger and could need a bit more time:
https://github.com/MelanX/ExtraDisks/issues/23
