### ISSUE TITLE
Creative Storage Disk (Items)

### ISSUE THREAD

**Issue by koalalord9999** [MelanX/ExtraDisks#24]
It would be cool to see the final iteration of larger disks.
With this addition, would add 2 new disks, and 1 new crafting component.
2 disks: 65536k / 262144k disks
1 component: Withering Processor - same recipe as other processors, with a nether star instead of diamond/iron/gold

With this new drive (262m) you can put 3 of those together as the same way all other disks are combined, into a single creative disk drive

**Comment by MelanX** [comment]
This mod already adds an infinite storage disk. And 65536k / 262144k, too.

**Comment by koalalord9999** [comment]
oh, thought it stopped at  16384k lol
