### ISSUE TITLE
1024k and 256k Disks not working.

### ISSUE THREAD

**Issue by ikonds** [MelanX/ExtraDisks#27]
Im on ATM6 To the Sky 1.0.7, ive been using a 256k Drive for the past couple of days, no problem, that filled up so i made a 1024k one too, 2 days later both the disks dont work.

They dont show up on the model of the Disk Drive block, they dont have that tooltip where it says how many items it has inside of it and i tried using a disk manipulator aswell and nothing happened, i tried spawning other disks in and they work fine, but all of my items were inside those disks and i lost 50hours of playtime, id like to find a solution to get my stuff back if possible.

**Comment by MelanX** [comment]
Can you send me your world/data/refinedstorage_disks.dat file, please? And a screenshot where you hover over one of the disks?

**Comment by ikonds** [comment]
I can provide you with a screenshot but i cant upload the file, how would i go about sending the file to you?

And here are the screenshots
![256kdisk](https://user-images.githubusercontent.com/83480904/116782168-85f61e80-aa7f-11eb-9832-191b4d40e023.png)
![1024kdisk](https://user-images.githubusercontent.com/83480904/116782174-8bebff80-aa7f-11eb-9f6c-6da66a3007f9.png)

**Comment by MelanX** [comment]
You could add it to a zip file

**Comment by ikonds** [comment]
I did and it says it doesnt support the format

**Comment by MelanX** [comment]
Strange, zip files are allowed on GitHub..

**Comment by ikonds** [comment]
[refinedstorage_disks.zip.zip](https://github.com/MelanX/ExtraDisks/files/6409781/refinedstorage_disks.zip.zip)

**Comment by ikonds** [comment]
nevermind i guess i didnt do something right

**Comment by MelanX** [comment]
Okay... I don't know what happened for you but the items are gone. I don't know why. 
But ExtraDisks can't be the reason. It just adds disks the same way refined storage does... I'm very sorry for you. I can't help you with that :/ Maybe at Refined Storages part it can be fixed?

**Comment by ikonds** [comment]
damn well thats a bit shitty :(

**Comment by ikonds** [comment]
alright well thanks for the help anyways 👍
