### ISSUE TITLE
Fluid Storage Blocks Not Working / Interface Issue

### ISSUE THREAD

**Issue by djfariel** [MelanX/ExtraDisks#30]
Hello, having an issue where fluid storage blocks are not taking items. When I place one, it shows up on the network controller and consumes energy. However, the interface for the storage block shows as being in whitelist mode by default. When I try to toggle the listing mode, it instead changes the redstone mode. In fact, changing any setting changes the redstone mode.  This only happens with ExtraDisks fluid blocks. Regular item blocks work as intended. 

https://gyazo.com/e3987642740336255847fa9cb70e10de

**Comment by MelanX** [comment]
closed by https://github.com/MelanX/ExtraDisks/commit/73c6a82245bb5c0062fdc8a475b13b1f348276ea
