### ISSUE TITLE
Infinite Storage Disk on Server Disconnects player past 1 billion items

### ISSUE THREAD

**Issue by taibhse-designs** [MelanX/ExtraDisks#31]
We player on a server hosted on apex, when a disk stores more than one billion items, the counter starts back over, any players trying to view the disks contents get disconnected with the error, 

ioexception, payload may be no bigger than 1048576

**Comment by MelanX** [comment]
The packet size is too high. You should delete all items with low durability. Less different items -> smaller packet -> no disconnect :)
If you find a mod which increases this packet size, please tell me. I can’t fix it, sorry.
You can remove these items with exporter. Or remove smaller disks to have a smaller packet size. Good luck :)
