### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by MelanX** [MelanX/ExtraDisks#33]
I want to change to license from MIT License to Apache 2.0 License. More information can be found here: https://www.apache.org/licenses/LICENSE-2.0.txt

Before I change it, I need permissions from all contributors of this project. All the users below, do you agree the change to Apache 2.0?
- [x] @TheDirectorX 
- [x] @Siriuo 
- [x] @cyber01 
- [x] @yappy2000d

**Comment by cyber01** [comment]
agree

**Comment by Siriuo** [comment]
All good with me...

**Comment by TheDirectorX** [comment]
https://github.com/MelanX/MoreVanillaTools/issues/28#issuecomment-922494947

**Comment by MelanX** [comment]
Reminder for @yappy2000d.
Everyone else could unsubscribe this thread in case they feel bothered.
![image](https://user-images.githubusercontent.com/26039509/158076631-e3959114-c994-4d2b-b254-5af73fba248f.png)

**Comment by yappy2000d** [comment]
Sorry, I'm currently preparing for an exam, so I have not been online. I'm not against changing the license.
