### ISSUE TITLE
Detector max range of 999 999 999

### ISSUE THREAD

**Issue by saquili** [MelanX/ExtraDisks#37]
### Minecraft version

1.16.5

### Extra Disks version

1.16.4-1.5.1

### Forge version

36.2.34

### The latest.log file

https://pastebin.com/sa3hGr9t

### Issue description

Hello, I am facing a problem with the detector, I am using infinite storage cell, and I want to have in stock more the detector allows me to set. The maximum number in detector block that saves is 999 999 999.

**Comment by MelanX** [comment]
Sorry, I’m not the person who can change the behavior of the detector. It’s part of the main mod Refined Storage.
