### ISSUE TITLE
infinite disk full??

### ISSUE THREAD

**Issue by czychuuu** [MelanX/ExtraDisks#38]
### Minecraft version

1.16.5

### Extra Disks version

extradisks-1.16.4-1.5.1

### Forge version

36.2.34

### The latest.log file

https://gist.github.com/czychuuu/072f6aa13ee88aaac98e6c2864269be2

### Issue description

Infinite disk full when there is more than 2B items (storage drawers vending upgrade and super fast importer)

https://prnt.sc/GYK5HBOVyPlk

### Steps to reproduce

1. import 2B items

**Comment by MelanX** [comment]
After this amount, you just can’t insert more of this type. It’s a feature from Refined Storage which prevents items from being deleted. You could downgrade refined storage, but this would result in item loss.
