### ISSUE TITLE
crash when pointing on a 1024k storage disk

### ISSUE THREAD

**Issue by daniel-for-github** [MelanX/ExtraDisks#4]
mc 14.4 , forge 61, refinedstorage-1.7,extradisks-1.0

see title , happens in creative and surv

remain in game on 64k 

regards

**Comment by MelanX** [comment]
Thank you 
Could you post a crash log via e.g. pastebin, please?

**Comment by MelanX** [comment]
I know the problem. It should be fixed if Refined Storage 1.7.1 is out (maybe this weekend). 
If Refined Storage 1.7.1 is out, this issue will be closed.

**Comment by MelanX** [comment]
Refined Storage 1.7.1 is out and this mod finally works now!
Here RS 1.7.1:
https://www.curseforge.com/minecraft/mc-mods/refined-storage/files/2829731
