### ISSUE TITLE
Infinite only allows 2.1M of liquid

### ISSUE THREAD

**Issue by Scampi-ml** [MelanX/ExtraDisks#41]
### Minecraft version

1.20.1

### Extra Disks version

3.0.0

### Forge version

47.1.3

### The latest.log file

No Log

### Issue description

Refined storage only allows 2.1M of liquid, despite having a INFINITE disk.
![image](https://github.com/MelanX/ExtraDisks/assets/1528455/15940e43-caa5-416b-9ade-98f99299dd08)

It seems there is a limit:
![image](https://github.com/MelanX/ExtraDisks/assets/1528455/61e3cc2d-5d4a-4dbc-80c9-c4987562060b)
![image](https://github.com/MelanX/ExtraDisks/assets/1528455/125734b9-45f8-4d61-8f31-3b55f68ce332)

My Setup:
![image](https://github.com/MelanX/ExtraDisks/assets/1528455/7e09cc92-8d74-4d3d-b9f6-19bafa169e77)

it was working fine but stop stopped sucking from the tank, no errors or anything

### Steps to reproduce

- I have 2 supreme black hole tanks from mod "Industrial forgoing"
- Have a Importer from RS suck out liquid from the tank.
- Does not want to suck anymore ...

### Other information

I am running ATM9

**Comment by MelanX** [comment]
That’s an internal limitation of Refined Storage to prevent an overflow, which results in losing this kind of item/fluid. 
I'm sorry, I can’t fix that.
