### ISSUE TITLE
Integer overflow with infinite storage disk

### ISSUE THREAD

**Issue by mberlin1** [MelanX/ExtraDisks#43]
### Minecraft version

1.20.1

### Extra Disks version

1.20.1-3.0.2

### Forge version

47.2.23

### The latest.log file

logfile of what, no crash here

### Issue description

Entire contents of disk have vanished because of integer overflow

### Steps to reproduce

Take compressium objects, decompress about 10 of them from level 9 compressium, enjoy the results.
I thought this issue was far in the past. apparently not.
![2024-04-27_00 25 28](https://github.com/MelanX/ExtraDisks/assets/3492348/81c8795d-befd-4e54-b115-1ad2f92460cf)

**Comment by MelanX** [comment]
#40
